package:
  name: perl-xml-libxslt
  version: "2.001000"

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-2.001000.tar.gz
  sha256: 26a1ce025d7e8f8259082061263cb8235ac1fbddafc72de143ee49154b64dcc8

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - pkg-config
  host:
    - perl
    - perl-xml-libxml
    - libxslt
  run:
    - perl
    - perl-xml-libxml
    - libxslt

test:
  # Perl 'use' tests
  imports:
    - XML::LibXSLT

about:
  home: http://metacpan.org/pod/XML-LibXSLT
  license: perl_5
  summary: 'Interface to GNOME libxslt library'
