package:
  name: perl-xml-xpath
  version: "1.47"

source:
  url: https://cpan.metacpan.org/authors/id/M/MA/MANWAR/XML-XPath-1.47.tar.gz
  sha256: c11e27f7c2b1bf9f966097faeb80cebda9d7f021f80afd479d46c10146912c50

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-xml-parser
    - perl-path-tiny

  run:
    - perl
    - perl-xml-parser

test:
  # Perl 'use' tests
  imports:
    - XML::XPath
    - XML::XPath::Boolean
    - XML::XPath::Builder
    - XML::XPath::Expr
    - XML::XPath::Function
    - XML::XPath::Literal
    - XML::XPath::LocationPath
    - XML::XPath::Node
    - XML::XPath::Node::Attribute
    - XML::XPath::Node::Comment
    - XML::XPath::Node::Element
    - XML::XPath::Node::Namespace
    - XML::XPath::Node::PI
    - XML::XPath::Node::Text
    - XML::XPath::NodeSet
    - XML::XPath::Number
    - XML::XPath::Parser
    - XML::XPath::PerlSAX
    - XML::XPath::Root
    - XML::XPath::Step
    - XML::XPath::Variable
    - XML::XPath::XMLParser

about:
  home: http://metacpan.org/pod/XML-XPath
  license: artistic_2
  summary: 'Parse and evaluate XPath statements.'
