{% set version = "1.1.0" %}
{% set sha256 = "881a42bf4fad70502862b389c1615ef8ce6f00092de7c3bacdb6a7e9c13aa6e3" %}

package:
  name: protestar
  version: {{ version }}

build:
  number: 1

source:
  url: https://github.com/refresh-bio/protestar/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - protestar > /dev/null

about:
  home: https://github.com/refresh-bio/protestar
  summary: "Protein Structures Archiver"
  license: GPL-3
  license_family: GPL
  license_file: LICENSE

extra:
  identifiers:
    - doi:10.1101/2023.07.20.549913
