{% set version = "1.1.0" %}
{% set sha256 = "fed1f75f6e713a5e6b5db5a4fdf64ca2d492d8089eab22bf6a9bc601eb6603bb" %}

package:
  name: protestar
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('protestar', max_pin='x.x.x') }}
    
source:
  url: https://github.com/refresh-bio/protestar/releases/download/v{{ version }}/protestar-complete-src.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - protestar > /dev/null

about:
  home: https://github.com/refresh-bio/protestar
  summary: "Protein Structures Archiver"
  license: GPL-3
  license_family: GPL
  license_file: LICENSE

extra:
  identifiers:
    - doi:10.1101/2023.07.20.549913
