{% set name = "LRphase" %}
{% set version = "0.7.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8f59cd97664d36e389f9cda66d73b05393639afd01acfa88662b6e9523b98cc3

build:
  number: 0
  entry_points:
    - LRphase = LRphase.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - biopython >=1.78
    - numpy >=1.20.1
    - pip
    - powerlaw >=1.4.6
    - pyliftover >=0.4
    - pysam >=0.16.0.1
    - powerlaw>=1.4.6
    - requests>=2.26.0
    - python
  run:
    - biopython >=1.78
    - numpy >=1.20.1
    - powerlaw >=1.4.6
    - pyliftover >=0.4
    - pysam >=0.16.0.1
    - powerlaw>=1.4.6
    - requests>=2.26.0
    - python

test:
  imports:
    - LRphase
  commands:
    - LRphase --help

about:
  home: "https://github.com/Boyle-Lab/LRphase.git"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Phasing individual long reads using known haplotype information."
